<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.eclipse.ee4j</groupId>
	<artifactId>cargo-tracker</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>Eclipse Cargo Tracker</name>
	<description>
        The project demonstrates how you can develop applications with the Jakarta EE platform using widely
        adopted architectural best practices like Domain-Driven Design (DDD).
    </description>
	<url>https://projects.eclipse.org/projects/ee4j.cargotracker/</url>

	<organization>
		<name>Eclipse Foundation</name>
		<url>https://www.eclipse.org/org/foundation/</url>
	</organization>

	<issueManagement>
		<system>github</system>
		<url>https://github.com/eclipse-ee4j/cargotracker/issues</url>
	</issueManagement>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
        <version.server.bom>8.0.5.GA-redhat-00005</version.server.bom>

		<!-- Arquillian properties -->
		<arquillian.core.version>1.4.1.Final</arquillian.core.version>
		<skipTests>true</skipTests>

		<!-- Codehaus Cargo plugin properties -->
		<cargo.version>1.8.1</cargo.version>
		<cargo.payara.container_id>glassfish4x</cargo.payara.container_id>
		<cargo.payara.download_uri>
			https://repo1.maven.org/maven2/fish/payara/distributions/payara/4.1.2.181/payara-4.1.2.181.zip
		</cargo.payara.download_uri>

		<!-- Application properties -->
		<webapp.databaseTempDir>/tmp</webapp.databaseTempDir>
		<webapp.graphTraversalUrl>
			http://localhost:8080/cargo-tracker/rest/graph-traversal/shortest-path
		</webapp.graphTraversalUrl>
	</properties>

	<dependencyManagement>
		<dependencies>
            <dependency>
                <groupId>org.jboss.bom</groupId>
                <artifactId>jboss-eap-ee-with-tools</artifactId>
                <version>${version.server.bom}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>

		<!-- Jakarta EE API v10 - mta generated -->
		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.inject</groupId>
			<artifactId>jakarta.inject-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.jms</groupId>
			<artifactId>jakarta.jms-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.json</groupId>
			<artifactId>jakarta.json-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.transaction</groupId>
			<artifactId>jakarta.transaction-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.websocket</groupId>
			<artifactId>jakarta.websocket-api</artifactId>
			<scope>provided</scope>
		</dependency>

		<!-- Jakarta EE API v10 -->
		<dependency>
			<groupId>jakarta.ejb</groupId>
			<artifactId>jakarta.ejb-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.websocket</groupId>
			<artifactId>jakarta.websocket-client-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.faces</groupId>
			<artifactId>jakarta.faces-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.batch</groupId>
			<artifactId>jakarta.batch-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.ws.rs</groupId>
			<artifactId>jakarta.ws.rs-api</artifactId>
			<scope>provided</scope>
		</dependency>

		<!-- The third-party dependencies this application has -->
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>2.10.6</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.4</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<version>12.0.0</version>
			<classifier>jakarta</classifier>
		</dependency>

		<!-- Test dependencies -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.1</version>
			<scope>test</scope>
		</dependency>

		<!-- Arquillian dependencies -->
		<dependency>
			<groupId>org.jboss.arquillian.junit</groupId>
			<artifactId>arquillian-junit-container</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- Resolvers are needed in the Arquillian tests. This is used for adding 
			all the runtime dependencies inside a testing war. -->
		<dependency>
			<groupId>org.jboss.shrinkwrap.resolver</groupId>
			<artifactId>shrinkwrap-resolver-impl-maven</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<finalName>cargo-tracker</finalName>
		<plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>payara</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<properties>
                <payara.version>6.2023.12</payara.version>
				<!-- Application properties -->
				<webapp.graphTraversalUrl>
					http://localhost:8080/cargo-tracker/rest/graph-traversal/shortest-path</webapp.graphTraversalUrl>
				<db.driverClass>org.h2.jdbcx.JdbcDataSource</db.driverClass>
				<!-- H2 file engine requires an absolute path, eg. ~/name, ./name or a full-qualified 
					path name (it should include driver name under Windows). -->
				<db.jdbcUrl>jdbc:h2:file:./cargo-tracker-data/cargo-tracker-database;create=true</db.jdbcUrl>
				<db.user />
				<db.password />
			</properties>
			<dependencies>
                <!-- We need a Jersey specific dependency for property name constants -->
                <dependency>
                    <groupId>org.glassfish.jersey.core</groupId>
                    <artifactId>jersey-server</artifactId>
                    <version>3.1.2</version>
                    <scope>provided</scope>
                </dependency>
                <!-- Embedding the JDBC driver in the WAR works in GlassFish -->
                <dependency>
                    <groupId>com.h2database</groupId>
                    <artifactId>h2</artifactId>
                    <version>2.1.214</version>
                    <scope>runtime</scope>
                </dependency>
                <dependency>
                    <groupId>fish.payara.extras</groupId>
                    <artifactId>payara-micro</artifactId>
                    <version>${payara.version}</version>
                    <scope>test</scope>
                </dependency>
                <!-- Payara Micro Managed Container Adapter -->
                <dependency>
                    <groupId>fish.payara.arquillian</groupId>
                    <artifactId>arquillian-payara-micro-managed</artifactId>
                    <version>3.0.alpha8</version>
                    <scope>test</scope>
                </dependency>
                <!-- Needed at the moment for Jakarta EE 10 support -->
                <dependency>
                    <groupId>fish.payara.arquillian</groupId>
                    <artifactId>payara-client-ee9</artifactId>
                    <version>3.0.alpha8</version>
                    <scope>test</scope>
                </dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>3.1.2</version>
					</plugin>
					<plugin>
						<groupId>org.codehaus.cargo</groupId>
						<artifactId>cargo-maven3-plugin</artifactId>
						<version>1.10.9</version>
						<configuration>
							<container>
								<containerId>payara</containerId>
								<artifactInstaller>
									<groupId>fish.payara.distributions</groupId>
									<artifactId>payara</artifactId>
									<version>${payara.version}</version>
								</artifactInstaller>
								<timeout>180000</timeout>
							</container>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>